modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="ferritymod"
version="0.1.1"
displayName="Ferrity"
displayURL="https://aboutvihaan7-8.yzz.me/ferrity"
logoFile="logo.png"
credits="just me :o "
authors="Vihaan7_8"
description="Basically Verity except he's always nice and dont become monster "

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.ferritymod]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.95,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ferritymod]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration